# Generated by Django 5.0.4 on 2024-06-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisa estar marcado para que a página possa ser exibida publicamente.'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, default=None, max_length=150, null=True, unique=True)),
                ('excerpt', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False, help_text='Este campo precisa estar marcado para que a página possa ser exibida publicamente.')),
                ('cover', models.ImageField(blank=True, default='', upload_to='post/%y/%m')),
                ('cover_in_post_content', models.BooleanField(default=True, help_text='se marcado, exibirá a capa dentro do post.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.category')),
                ('tags', models.ManyToManyField(blank=True, default='', to='project.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
