# Generated by Django 5.0.4 on 2024-06-13 21:37

import site_setup.utils.model_vlidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assests/favicon/%y/%m/', validators=[site_setup.utils.model_vlidators.validators_image]),
        ),
    ]
